#!/bin/sh

sed -i -e "s;\ \ ;;g" -e "s;\, ;\,;g" test_ver2.csv
awk -F'"' -v OFS='' '{ for (i=2; i<=NF; i+=2) gsub(",", "\,", $i) } 1' test_ver2.csv > test.csv
sed -i -e "s;\";;g" test.csv

sed -i -e "s;\ \ ;;g" -e "s;\, ;\,;g" train_ver2.csv
awk -F'"' -v OFS='' '{ for (i=2; i<=NF; i+=2) gsub(",", "\,", $i) } 1' train_ver2.csv > train.csv
sed -i -e "s;\";;g" train.csv
